### ISSUE TITLE
Recursor/forwarders?

### ISSUE THREAD

**Issue by ghost** [aescanero/docker-powerdns-admin-alpine#3]
Hey guys,

Thank you very much for providing that setup.

Thus, I am wondering if there is any possibility to add recursor/forwarder to that setup?

In my case, I ve created internal powerdns server, I ve added my machines to use that, however, once linux machines are added to use my internal dns server they do not have internet access. I know that you can just add 2 dns nameservers in /etc/resolv.conf like internal-ip-dns-server and 8.8.8.8/1.1.1.1. Nevertheless, due to some limitations of NetworkManager and dnsmasq service I would prefer to have just one internal dns server which can forward all requests and if needed, forward queries to 8.8.8.8. Any suggestions on that please?

Thank you

**Comment by aescanero** [comment]
Powerdns don't have a integrated recursor. To do this you need a external service (https://www.powerdns.com/recursor.html), If you need to use a dns server with forward or recursion then I would prefer to use bind in your setup.

**Comment by Pechsopha** [comment]
@aescanero Could you help me? When I set up Server PowerDNS-admin already and I assigned 2 DNS server(PowerDNS server and 8.8.8.8) on my pfsence. Ubuntu, phone(android, ios) can not assess all dns record Accept only Window
